#!/usr/bin/env python3
"""
Training Integration Script
Generated by CapibaraGPT-v2 Pipeline: pipeline_1753275027
Generated at: 2025-07-23T12:50:44.044825
"""

import sys
import json
from pathlib import Path

import logging
logger = logging.getLogger(__name__)

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

def main():
    """Run training with pipeline-generated data."""
    
    # Load training configuration
    config_path = Path(__file__).parent / "training_config.json"
    with open(config_path, 'r', encoding='utf-8') as f:
        config = json.load(f)
    
    logger.info(" Starting CapibaraGPT-v2 Training")
    logger.info(f" Pipeline ID: {config['dataset_info']['pipeline_id']}")
    logger.info(f" Total records: {config['dataset_info']['total_records']}")
    logger.info(f"️  Data types: {', '.join(config['dataset_info']['data_types'])}")
    
    # Import training module
    try:
        from capibara.training import TrainingOrchestrator
        
        # Initialize training orchestrator
        trainer = TrainingOrchestrator(config)
        
        # Start training
        result = trainer.run_training()
        
        logger.info(" Training completed successfully!")
        return result
        
    except ImportError as e:
        logger.warning(f" Training module not available: {e}")
        logger.info(" Alternative: Use generated datasets with your preferred training framework")
        logger.info(f"   Train data: {config['data_paths']['train']}")
        logger.info(f"   Validation data: {config['data_paths']['validation']}")
        return None

if __name__ == "__main__":
    main()
