# Copyright 2018 The JAX Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities for pseudo-random number generation.

The :mod:`jax.random` package provides a number of routines for deterministic
generation of sequences of pseudorandom numbers.

Basic usage
-----------

>>> seed = 1701
>>> num_steps = 100
>>> key = jax.random.key(seed)
>>> for i in range(num_steps):
...   key, subkey = jax.random.split(key)
...   params = compiled_update(subkey, params, next(batches))  # doctest: +SKIP

PRNG keys
---------

Unlike the *stateful* pseudorandom number generators (PRNGs) that users of NumPy and
SciPy may be accustomed to, JAX random functions all require an explicit PRNG state to
be passed as a first argument.

The random state is described by a special array element type that we call a **key**,
usually generated by the :py:func:`jax.random.key` function::

    >>> from capibara.jax import random
    >>> key = random.key(0)
    >>> key
    Array((), dtype=key<fry>) overlaying:
    [0 0]

This key can then be used in any of JAX's random number generation routines::

    >>> random.uniform(key)
    Array(0.947667, dtype=float32)

Note that using a key does not modify it, so reusing the same key will lead to the same result::

    >>> random.uniform(key)
    Array(0.947667, dtype=float32)

If you need a new random number, you can use :meth:`jax.random.split` to generate new subkeys::

    >>> key, subkey = random.split(key)
    >>> random.uniform(subkey)
    Array(0.00729382, dtype=float32)
"""

import numpy as np
from typing import Any, Optional, Tuple, Union

# Try to import real JAX random
try:
    from jax import random as jax_random
    HAS_JAX = True

    # Re-export all JAX random functions
    PRNGKey = jax_random.PRNGKey
    ball = jax_random.ball
    bernoulli = jax_random.bernoulli
    beta = jax_random.beta
    bits = jax_random.bits
    categorical = jax_random.categorical
    cauchy = jax_random.cauchy
    choice = jax_random.choice
    dirichlet = jax_random.dirichlet
    exponential = jax_random.exponential
    fold_in = jax_random.fold_in
    gamma = jax_random.gamma
    gumbel = jax_random.gumbel
    key = jax_random.key
    key_data = jax_random.key_data
    laplace = jax_random.laplace
    logistic = jax_random.logistic
    loggamma = getattr(jax_random, 'loggamma', lambda k, a: gamma(k, a))
    lognormal = getattr(jax_random, 'lognormal', lambda k, s=1.0: np.exp(normal(k) * s))
    maxwell = jax_random.maxwell
    multivariate_normal = jax_random.multivariate_normal
    normal = jax_random.normal
    orthogonal = jax_random.orthogonal
    pareto = jax_random.pareto
    permutation = jax_random.permutation
    poisson = jax_random.poisson
    randint = jax_random.randint
    rayleigh = jax_random.rayleigh
    split = jax_random.split
    t = jax_random.t
    triangular = jax_random.triangular
    truncated_normal = jax_random.truncated_normal
    uniform = jax_random.uniform
    weibull_min = jax_random.weibull_min

except ImportError:
    HAS_JAX = False

    # Fallback implementations using numpy
    _rng = np.random.default_rng()

    def PRNGKey(seed: int) -> np.ndarray:
        """Create a PRNG key from a seed."""
        return np.array([0, seed], dtype=np.uint32)

    def key(seed: int) -> np.ndarray:
        """Create a PRNG key from a seed."""
        return PRNGKey(seed)

    def split(key: np.ndarray, num: int = 2) -> Tuple[np.ndarray, ...]:
        """Split a PRNG key into multiple keys."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        return tuple(PRNGKey(seed + i) for i in range(num))

    def fold_in(key: np.ndarray, data: int) -> np.ndarray:
        """Fold data into a PRNG key."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        return PRNGKey(seed ^ data)

    def uniform(key: np.ndarray, shape: tuple = (), minval: float = 0.0, maxval: float = 1.0, dtype=np.float32) -> np.ndarray:
        """Generate uniform random numbers."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.uniform(minval, maxval, shape).astype(dtype)

    def normal(key: np.ndarray, shape: tuple = (), dtype=np.float32) -> np.ndarray:
        """Generate normal random numbers."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.standard_normal(shape).astype(dtype)

    def randint(key: np.ndarray, shape: tuple, minval: int, maxval: int, dtype=np.int32) -> np.ndarray:
        """Generate random integers."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.integers(minval, maxval, shape, dtype=dtype)

    def bernoulli(key: np.ndarray, p: float = 0.5, shape: tuple = ()) -> np.ndarray:
        """Generate Bernoulli random variables."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.random(shape) < p

    def categorical(key: np.ndarray, logits: np.ndarray, axis: int = -1, shape: Optional[tuple] = None) -> np.ndarray:
        """Generate categorical random variables."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        probs = np.exp(logits - np.max(logits, axis=axis, keepdims=True))
        probs = probs / np.sum(probs, axis=axis, keepdims=True)
        if shape is None:
            shape = logits.shape[:-1]
        return rng.choice(logits.shape[-1], size=shape, p=probs.flatten())

    def choice(key: np.ndarray, a: Union[int, np.ndarray], shape: tuple = (), replace: bool = True, p: Optional[np.ndarray] = None) -> np.ndarray:
        """Random choice from array."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.choice(a, size=shape, replace=replace, p=p)

    def permutation(key: np.ndarray, x: Union[int, np.ndarray]) -> np.ndarray:
        """Random permutation."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        if isinstance(x, int):
            return rng.permutation(x)
        return rng.permutation(x)

    def gamma(key: np.ndarray, a: float, shape: tuple = (), dtype=np.float32) -> np.ndarray:
        """Generate gamma random variables."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.gamma(a, size=shape).astype(dtype)

    def beta(key: np.ndarray, a: float, b: float, shape: tuple = (), dtype=np.float32) -> np.ndarray:
        """Generate beta random variables."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.beta(a, b, size=shape).astype(dtype)

    def exponential(key: np.ndarray, shape: tuple = (), dtype=np.float32) -> np.ndarray:
        """Generate exponential random variables."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.exponential(size=shape).astype(dtype)

    def poisson(key: np.ndarray, lam: float, shape: tuple = (), dtype=np.int32) -> np.ndarray:
        """Generate Poisson random variables."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.poisson(lam, size=shape).astype(dtype)

    def dirichlet(key: np.ndarray, alpha: np.ndarray, shape: tuple = (), dtype=np.float32) -> np.ndarray:
        """Generate Dirichlet random variables."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.dirichlet(alpha, size=shape).astype(dtype)

    def multivariate_normal(key: np.ndarray, mean: np.ndarray, cov: np.ndarray, shape: tuple = (), dtype=np.float32) -> np.ndarray:
        """Generate multivariate normal random variables."""
        seed = int(key[1]) if len(key) > 1 else int(key[0])
        rng = np.random.default_rng(seed)
        return rng.multivariate_normal(mean, cov, size=shape).astype(dtype)

    def key_data(key: np.ndarray) -> np.ndarray:
        """Get raw key data."""
        return key

    # Placeholder functions
    def ball(*args, **kwargs): return uniform(args[0])
    def bits(*args, **kwargs): return randint(args[0], kwargs.get('shape', ()), 0, 2**32 - 1, np.uint32)
    def cauchy(*args, **kwargs): return normal(args[0], kwargs.get('shape', ()))
    def gumbel(*args, **kwargs): return normal(args[0], kwargs.get('shape', ()))
    def laplace(*args, **kwargs): return normal(args[0], kwargs.get('shape', ()))
    def logistic(*args, **kwargs): return normal(args[0], kwargs.get('shape', ()))
    def loggamma(*args, **kwargs): return gamma(args[0], 1.0, kwargs.get('shape', ()))
    def lognormal(*args, **kwargs): return np.exp(normal(args[0], kwargs.get('shape', ())))
    def maxwell(*args, **kwargs): return normal(args[0], kwargs.get('shape', ()))
    def orthogonal(*args, **kwargs): return np.eye(kwargs.get('n', 2))
    def pareto(*args, **kwargs): return uniform(args[0], kwargs.get('shape', ()))
    def rayleigh(*args, **kwargs): return normal(args[0], kwargs.get('shape', ()))
    def t(*args, **kwargs): return normal(args[0], kwargs.get('shape', ()))
    def triangular(*args, **kwargs): return uniform(args[0], kwargs.get('shape', ()))
    def truncated_normal(*args, **kwargs): return normal(args[0], kwargs.get('shape', ()))
    def weibull_min(*args, **kwargs): return uniform(args[0], kwargs.get('shape', ()))

__all__ = [
    'PRNGKey', 'ball', 'bernoulli', 'beta', 'bits', 'categorical',
    'cauchy', 'choice', 'dirichlet', 'exponential', 'fold_in',
    'gamma', 'gumbel', 'key', 'key_data', 'laplace', 'logistic',
    'loggamma', 'lognormal', 'maxwell', 'multivariate_normal',
    'normal', 'orthogonal', 'pareto', 'permutation', 'poisson',
    'randint', 'rayleigh', 'split', 't', 'triangular',
    'truncated_normal', 'uniform', 'weibull_min',
]
